### ISSUE TITLE
謎の沈黙

### ISSUE THREAD

**Issue by fono09** [fono09/ttRelay#2]
WebSocketで再接続を行う実装にしたのにも関わらず，
数日放置すると勝手に死んでエラーも吐かなくなる．

**Comment by fono09** [comment]
nginxまでは`wss://`だけど，バックエンドは`ws://`だからもしかすると，普通にタイムアウトしているのかも？それも含めて(ping/pongで死亡判定すると思うんだけどなぁ)

**Comment by fono09** [comment]
https://github.com/theturtle32/WebSocket-Node/issues/337
見事に踏み抜いたっぽい．ライブラリ差し替えるかパッチ当てるか．

**Comment by massongit** [comment]
https://github.com/pladaria/reconnecting-websocket
こういうのもあるっぽい。
